# Generated by Django 4.1.3 on 2022-11-16 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_quiz_question"),
    ]

    operations = [
        migrations.CreateModel(
            name="quiz_submissions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=255)),
                ("remain", models.TextField()),
                ("my_ans", models.TextField()),
                ("score", models.IntegerField()),
            ],
        ),
    ]
