# Generated by Django 4.1.3 on 2022-11-17 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_quiz_submissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz_question",
            name="question_image",
            field=models.ImageField(default="", upload_to=""),
        ),
    ]
