# Generated by Django 4.1.3 on 2022-11-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_quiz_question_question_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz_question",
            name="option_1_image",
            field=models.ImageField(default="", upload_to=""),
        ),
        migrations.AddField(
            model_name="quiz_question",
            name="option_2_image",
            field=models.ImageField(default="", upload_to=""),
        ),
        migrations.AddField(
            model_name="quiz_question",
            name="option_3_image",
            field=models.ImageField(default="", upload_to=""),
        ),
        migrations.AddField(
            model_name="quiz_question",
            name="option_4_image",
            field=models.ImageField(default="", upload_to=""),
        ),
    ]
